version: '3.3'

networks:
  flask_network:
    name: flask_network
    
  


services:

  flask : 
    image : flask_test_server:latest
    container_name: flask_server
    restart: always
    ports : 
      - 5000:5000
    networks:
      - flask_network
 
