version: '3.3'

networks:
  flask_network:
    name: flask_network
    
  
services:
  flask:
    image: flask_mysql:latest
    ports:
      - 5000:5000
    networks:
      - flask_network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: flask_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER : user
      MYSQL_PASSWORD : user
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    networks:
      - flask_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - flask_network     