version : '3.9'

networks:
  services_network:
    name: services_network

services:
  resis-db:
    image: redis:latest
    container_name: redis-services
    command: redis-server --save 1 60 --loglevel warning --requirepass root
    ports:
      - 6379:6379
    volumes:
      - chache:/data
    networks:
      - services_network
    

volumes:
  chache:
    driver: local
    